name: CI Test

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          
      - uses: ./.github/actions/setup-and-build

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps --only-shell

      - name: Test
        # Run all vitest tests, but not playwright, for brevity
        run: npx vitest run